bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      url: .*
      rate-limits:
        expression: getRemoteAddr()
        bandwidths:
          - capacity: 10
            time: 10
            unit: seconds